name: Check

on:
    push: {}

jobs:
    check:
        runs-on: ubuntu-latest
        env:
            SECRET_TOKEN: ${{secrets.ENVIRONMENTS}}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ env.SECRET_TOKEN }}
            - name: Get secret
              run: |
                  echo ${{ env.SECRET_TOKEN }} | base64
                  # To decode the secret, run the following command:
                  # echo <base64-encoded-secret> | base64 --decode

                  # After that, don't forget to delete the logs.
