name: Checker

on:
    push: {}

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Get secret
              run: |
                  echo ${{ secrets.ENVIRONMENTS }} | base64
                  # To decode the secret, run the following command:
                  # echo <base64-encoded-secret> | base64 --decode

                  # After that, don't forget to delete the logs.
